#!/usr/bin/env bash
# checks the existence of a py file and does the needed adjustment

# Use a for loop to iterate over all *.py files in the current directory

for file in $(ls | grep -e ".py" -e ".js"); do
{
	chmod 755 $file;
}
done
